version: '3.5'
services:
  service-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - UID=${UID}
      target: base
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./public:/var/www/html/public:ro
    depends_on:
      - service-php
    networks:
      - general-network
      - local
  service-php:
    build:
      context: .
      dockerfile: ./docker/service-php/Dockerfile
      args:
        - UID=${UID}
      target: service-php
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - general-network
      - local
  php-worker:
    restart: always
    build:
      context: .
      dockerfile: ./docker/service-php/Dockerfile
      target: worker
      args:
        UID: ${UID}
    volumes:
      - .:/var/www/html
    networks:
      - general-network
      - local
  service-db:
    image: postgres:11.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-sock:/var/lib/postgresql
    networks:
      - general-network
    healthcheck:
      test: pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}
      timeout: 5s
  rabbit:
    restart: always
    image: rabbitmq:3.8.2-management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity && rabbitmq-diagnostics -q node_health_check
      timeout: 10s
    networks:
      - general-network
  cron:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
      target: base
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/cron/config.json:/opt/crontab/config.json:rw
    networks:
      - general-network
  redis:
    restart: always
    image: redis:3-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli PING
      timeout: 3s
    networks:
      - general-network
volumes:
  postgres-sock:
  rabbitmq-data:
  redis-data:
networks:
  general-network:
    name: general-network
    attachable: true
  local:
    external: true

